version: '3.8'
services:
  front:
    # コンテナ名はフロント
    container_name: frontend
    # ビルドコンテキストはカレントディレクトリ
    build:
      context: .
      dockerfile: infra/frontend/Dockerfile
    # カレントディレクトリ内の`/app`のファイル・フォルダをコンテナにマウントします
    volumes:
      - ./app/frontend/:/usr/src/app
      # mode_modules用の永続化Volumeを作成して2回目以降のnode_modulesの呼び出しを高速化
      - node_modules_volume:/app/node_modules
    # npmを使って起動する
    command: sh -c "npm start"
    ports:
      # デフォルトの3000ポートを使う
      - "3000:3000"
    # ホットリロードを有効化
    environment:
      - CHOKIDAR_USEPOLLING=true
  back:
    restart: always
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    container_name: backend
    working_dir: '/root/src'
    tty: true
    ports:
     - "3001:3001"
    volumes:
      - ${SRC_PATH}:/root/src

volumes:
  node_modules_volume: